### ISSUE TITLE
Rreporte de Proyecto Diseño de Libreria en App de Escritorio

### ISSUE THREAD

**Issue by IrvinSanchez-dev** [SistemasTecTlaxiaco/actividad-6-diseno-de-app-con-windows-form-topicos_a-4bs-idm#1]
[REPORTE DE PRACTICA LIBRERIA DE APP DE ESCRITORIO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-diseno-de-app-con-windows-form-topicos_a-4bs-idm/files/14680783/REPORTE.DE.PRACTICA.LIBRERIA.DE.APP.DE.ESCRITORIO.pdf)

INTEGRANTES DE EQUIPO:

DIEGO CRUZ CRUZ
IRVIN JIMENEZ SANCHEZ
MARCO URIEL ROSAS GARCIA

**Comment by Nancy-0714** [comment]
Si cumplieron con los requisitos del criterio.
Calificación 20

**Comment by josealfredo79** [comment]
Esta bien..pero en esta practica es diseño de la biblioteca y sus metodos en la proxima practica..se implementa...por favor..
